name: 'gradle-dependency-diff-action'
description:
  'Report the Gradle dependency differences caused by the Pull Request'
author: 'be-hase'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  tool-version:
    description:
      'Version of
      dependency-tree-diff-version(https://github.com/JakeWharton/dependency-tree-diff).'
    required: false
    default: '1.2.1'
  configurations:
    description:
      'Target dependency configurations. Multiple values can be specified,
      separated by commas.'
    required: false
    default: 'runtimeClasspath'
  post-pr-comment:
    description:
      'If true, posts a PR comment when there are dependency differences.'
    required: false
    default: 'true'
  update-pr-body:
    description:
      'If true, updates the PR body when there are dependency differences.'
    required: false
    default: 'false'
  assign-label:
    description:
      'If true, adds a PR label when there are dependency differences.'
    required: false
    default: 'true'
  label-name:
    description: 'Label name used with assign-label.'
    required: false
    default: 'dependencies-change'
  upload-artifact:
    description:
      'If true, uploads the dependency differences as a text file to the actions
      artifact.'
    required: false
    default: 'true'
  token:
    description: 'Token used by this action.'
    required: false
    default: ${{ github.token }}
  custom-endpoint-url:
    description:
      'By default, the report is recorded in GitHub checks. If you want to send
      it to a custom server, please use this option. This feature is
      experimental and may change without notice.'
    required: false
  custom-endpoint-headers:
    description: 'The header used when sending to a custom endpoint.'
    required: false

runs:
  using: node20
  main: dist/index.js
