name: 'gradle-dependency-diff-action'
description: 'Report the Gradle dependency differences caused by the Pull Request'
author: 'be-hase'

branding:
  icon: 'heart'
  color: 'red'

#inputs:
#  milliseconds:
#    description: 'Your input description here'
#    required: true
#    default: '1000'

runs:
  using: node20
  main: dist/index.js
